=== kyj0706/Increpas_WebStudy/2022_1226_XmlTest/src/main/webapp/person.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT persons (person*) >
	<!ELEMENT person (name,age,tel) >
		<!ELEMENT name (#PCDATA)>
			<!ATTLIST name nickname   CDATA #REQUIRED>
			<!ATTLIST name familyname CDATA #IMPLIED>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT tel (#PCDATA)>	
		    <!ATTLIST tel hometel CDATA #REQUIRED>

=== kyj0706/Increpas_WebStudy/2022_1226_XmlTest/src/main/webapp/person.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE persons SYSTEM "person.dtd">
<!-- Root Element(요소) -->
<persons>
	<person>
	    <!-- nickname : Attribute(속성) -->
		<name nickname="원님" familyname="일">일길동</name>
		<age>33</age>
		<tel hometel="02-111-1111">010-111-1111</tel>
	</person>
	<person>
	    <!-- nickname : Attribute(속성) -->
		<name nickname="투님">이길동</name>
		<age>22</age>
		<tel hometel="031-111-1111">010-222-2222</tel>
	</person>
	<person>
	    <!-- nickname : Attribute(속성) -->
		<name nickname="삼님">삼길동</name>
		<age>55</age>
		<tel hometel="02-555-0555">010-555-5555</tel>
	</person>

</persons>
